### ISSUE TITLE
[FRONTEND] Form page (desktop)

### ISSUE THREAD

**Issue by djeck1432** [djeck1432/spotnet#241] opened 2024-11-22 10:00 UTC
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Rework form page following figma (ONLY DESKTOP VERSION)
3. Make sure that all backend stuff is not broken and work properly
4. Adjust test cases if it's needed
5. Ask me in telegram(djeck_vorobey1) to get access to figma, send me your email in message

**Comment by Ayoazeez26** [comment] 2024-11-22 10:02
Hi @djeck1432 I would like to work on this
I like orange
I would handle this by using the figma design to rework the form and make it look as expected
I would make sure all functionalities work as intended before making a PR
ETA - 1 day

**Comment by dahtee** [comment] 2024-11-22 10:05
Can I work on this please?

**Comment by DanielEmmanuel1** [comment] 2024-11-22 10:10
Let me handle this issue!

Hello I'm a frontend developer and a new contributor with good experience in creating crispy UI design and would love the opportunity to work on this. Thank u

**Comment by Supa-mega** [comment] 2024-11-22 10:13
Can I be assigned to this?

**Comment by djeck1432** [comment] 2024-11-22 10:22
@DanielEmmanuel1  read guideline

**Comment by djeck1432** [comment] 2024-11-22 10:22
@Supa-mega, your account is suspicious empty, not sure that you can manage it

**Comment by djeck1432** [comment] 2024-11-22 10:23
@dahtee if you apply again to issues which labeled `ONLY_FOR_NEW_CONTRIBUTORS` and being `returned contributors` you won't have any further issue anymore. please, respect new contributors

**Comment by ekumamatthew** [comment] 2024-11-22 10:25
Could I take a shot at this? I like oranges

**Closed** 2024-11-25 18:26 UTC
Labels: good first issue, FE, ONLY_FOR_NEW_CONTRIBUTORS, ODHack10
